SELECT A.FULLNAME, M.RATINGCODE, COUNT(*)
FROM ACTOR3679 A

INNER JOIN CASTING3679 C
ON A.ACTORNO = C.ACTORNO

INNER JOIN MOVIE3679 M
ON M.MOVIENO = C.MOVIENO

GROUP BY M.RATINGCODE, A.FULLNAME
ORDER BY A.FULLNAME, M.RATINGCODE ASC;