1111111 Union
SELECT FullName, Gender FROM STUDENT
UNION
SELECT FullName, Gender FROM STAFF

ORDER BY Gender, FullName;

2222222
SELECT *
FROM ATTENDANCE

WHERE Score < (SELECT AVG(Score) FROM ATTENDANCE);

3333333
SELECT Stf.FullName, Smnr.SemID
FROM STAFF Stf
LEFT OUTER JOIN SEMINAR Smnr
ON Stf.STFID = Smnr.STFID

4444444
SELECT Std.FullName, Smnr.Title, Smnr.Score
FROM SEMINAR Smnr
RIGHT OUTER JOIN STUDENT Std
ON Std.StuID = Smnr.STUID
